"""
Thread-safe in-memory alert store for the monitoring system.
Stores alerts generated by background monitoring agents.
"""

import threading
import uuid
from datetime import datetime, timezone
from typing import List, Optional


class Alert:
    """Represents a single system alert."""

    def __init__(self, alert_type: str, severity: str, title: str, message: str, source: str = "monitor"):
        self.id = str(uuid.uuid4())[:8]
        self.alert_type = alert_type          # low_stock | shipment_delay | risk | system
        self.severity = severity              # info | warning | critical
        self.title = title
        self.message = message
        self.source = source
        self.timestamp = datetime.now(timezone.utc).isoformat()
        self.read = False

    def to_dict(self):
        return {
            "id": self.id,
            "alert_type": self.alert_type,
            "severity": self.severity,
            "title": self.title,
            "message": self.message,
            "source": self.source,
            "timestamp": self.timestamp,
            "read": self.read,
        }


class AlertStore:
    """
    Thread-safe singleton store for system alerts.
    Keeps the most recent 100 alerts in memory.
    """

    _instance = None
    _lock = threading.Lock()
    MAX_ALERTS = 100

    def __new__(cls):
        with cls._lock:
            if cls._instance is None:
                cls._instance = super().__new__(cls)
                cls._instance._initialized = False
            return cls._instance

    def __init__(self):
        if self._initialized:
            return
        self._alerts: List[Alert] = []
        self._store_lock = threading.Lock()
        self._recent_keys: set = set()   # dedup keys: "type:identifier"
        self._initialized = True

    def add_alert(self, alert_type: str, severity: str, title: str, message: str,
                  dedup_key: Optional[str] = None, source: str = "monitor") -> Optional[Alert]:
        """
        Add a new alert. If dedup_key is provided, skip if we already have
        an unread alert with the same key (prevents duplicate spam).
        """
        with self._store_lock:
            if dedup_key and dedup_key in self._recent_keys:
                return None

            alert = Alert(alert_type, severity, title, message, source)
            self._alerts.insert(0, alert)  # newest first

            if dedup_key:
                self._recent_keys.add(dedup_key)

            # Cap at MAX_ALERTS
            if len(self._alerts) > self.MAX_ALERTS:
                removed = self._alerts.pop()
                # Clean up dedup key for removed alert
                pass

            return alert

    def get_alerts(self, unread_only: bool = False, limit: int = 50) -> List[dict]:
        """Get alerts, optionally filtered to unread only."""
        with self._store_lock:
            alerts = self._alerts
            if unread_only:
                alerts = [a for a in alerts if not a.read]
            return [a.to_dict() for a in alerts[:limit]]

    def get_unread_count(self) -> int:
        """Get count of unread alerts."""
        with self._store_lock:
            return sum(1 for a in self._alerts if not a.read)

    def mark_read(self, alert_id: str) -> bool:
        """Mark a single alert as read."""
        with self._store_lock:
            for alert in self._alerts:
                if alert.id == alert_id:
                    alert.read = True
                    return True
            return False

    def mark_all_read(self):
        """Mark all alerts as read and clear dedup keys so new alerts can come in."""
        with self._store_lock:
            for alert in self._alerts:
                alert.read = True
            self._recent_keys.clear()

    def clear(self):
        """Clear all alerts."""
        with self._store_lock:
            self._alerts.clear()
            self._recent_keys.clear()


# Singleton instance
alert_store = AlertStore()
